name: CI / Build & Deploy IG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install SUSHI
        run: npm install -g fsh-sushi

      - name: Download IG Publisher
        run: |
          curl -L -o publisher.jar \
            https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar

      - name: Setup Ruby (para Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Install Jekyll gem
        run: gem install jekyll

      - name: Compile FSH y generar recursos
        working-directory: ./input
        run: sushi .

      - name: Run IG Publisher
        run: |
          java -jar publisher.jar -ig input -tx https://tx.fhir.org

  test-artifact:
    name: Test artifact upload
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy file
        run: |
          mkdir -p ./output
          echo hello > ./output/world.txt

      - name: Upload IG output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./output/world.txt
          
  download-artifact:
    name: Download IG output
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R

  deploy:
    name: Deploy IG to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
