name: CI / Build & Deploy IG (con artifacts)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install SUSHI
        run: npm install -g fsh-sushi

      - name: Download IG Publisher
        run: |
          curl -L -o publisher.jar \
            https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar

      - name: Setup Ruby (para Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Install Jekyll gem
        run: gem install jekyll

      - name: Compile FSH y generar recursos
        run: sushi .

      - name: Run IG Publisher
        run: |
          java -jar publisher.jar -ig ./ -tx https://tx.fhir.org

      - name: Upload todo el output como artifact
        uses: actions/upload-artifact@v4
        with:
          name: ig-output
          path: output/**

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository (necesario para peaceiris)
        uses: actions/checkout@v3

      - name: Download artifact con la carpeta output/
        uses: actions/download-artifact@v4
        with:
          name: ig-output

      # A estas alturas, el runner tiene ./output/ completo

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
