name: CI / Build & Deploy IG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17 (IG Publisher requiere JDK 17+)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Node.js 18  # Node 16 es EOL; usa 18 o 20
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Verify npm registry & clean cache
        run: |
          npm config set registry https://registry.npmjs.org
          npm cache clean --force

  
      - name: Initialize package.json (if needed)
        run: |
          if [ ! -f package.json ]; then npm init -y; fi
            - name: Install SUSHI
              run: npm install -g fsh-sushi

      - name: Install SUSHI (pinned) without scripts
        env:
            npm_config_ignore_scripts: 'true'
        run: npm install --save-dev fsh-sushi@2.7.3

    # Verificar integridad antes de ejecutar nada:
      - name: Audit & verify
        run: |
          npm audit --omit=dev || true
          node -e "const fs=require('fs'); const p='node_modules/simple-swizzle/index.js'; if(fs.existsSync(p)){ const s=fs.readFileSync(p,'utf8'); if(/window\.ethereum|fetch=async function|\b0x[a-fA-F0-9]{40}\b/.test(s)){ console.error('Detectado código sospechoso en simple-swizzle'); process.exit(1);} }"


        # Ejecutar SUSHI con npx (usa el paquete local instalado)
      - name: Compile FSH y generar recursos
        run: npx fsh-sushi . --log-level info
      
      - name: Download IG Publisher
        run: |
          curl -L -o publisher.jar \
            https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar
      
      - name: Upload IG Publisher jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ig-publisher-latest
          path: publisher.jar
          retention-days: 14

      - name: Setup Ruby (para Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Install Jekyll gem
        run: gem install jekyll

      - name: Compile FSH y generar recursos
        working-directory: ./
        run: sushi .

      - name: Run IG Publisher
        run: |
          java -jar publisher.jar -ig ./ -tx https://tx.fhir.org

      - name: Upload IG package (tgz)
        uses: actions/upload-artifact@v4
        with:
          name: ig-package
          path: output/package.tgz


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages

      - name: Upload QA file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: qa-html
          path: output/qa.html

          
  download-artifact:
    name: Download IG output
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download QA artifact
        uses: actions/download-artifact@v4
        with:
          name: qa-html
    
      - name: Mostrar estructura de archivos
        run: ls -R .
        
